# SPDX-FileCopyrightText: 2026 Alexandru Ciobanu (alex+git@ciobanu.org)
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [
    "Package.resolved",
    "Sources/VoiceActivationApp/Resources/CaptureEnd.wav",
    "Sources/VoiceActivationApp/Resources/CaptureStart.wav",
    "Sources/VoiceActivationApp/Resources/VoiceActivation.icns",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Alexandru Ciobanu (alex+git@ciobanu.org)"
SPDX-License-Identifier = "MIT"
